### ISSUE TITLE
GPU device instance has been suspended, SharpGen.Runtime.SharpGenException

### ISSUE THREAD

**Issue by anose001** [EvergineTeam/EverSneaks#4] opened 2023-11-20 05:31 UTC
When testing out the App via a Windows machine this error occurred. I was able to enter the DetailsPage and navigate out a couple of times. Entering the DetailsPage is always very slow (2-3s). Navigating out is rather quick. When clicking on the Sneaker tile for the third or fourth time to enter this error occurs.

`SharpGen.Runtime.SharpGenException: 'HRESULT: [0x887A0005], Message: [The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.]'`

![Error_SneakerApp_On_WindowsMachine](https://github.com/EvergineTeam/EverSneaks/assets/11502664/b37cf132-d89d-400f-8cd2-b90f47d6f9bd)

**Comment by Jorgemagic** [comment] 2023-12-20 11:27
Hi anose001,

Thank you for your feedback. The delay in loading the detailsPage was due to the simultaneous loading of all 3D resources when navigating to the detailsPage. To address this issue, we have implemented the DetailsPage as a Singleton. Now, you may experience a slow load only the first time, but subsequent navigations will be faster since the Page is loaded.

Additionally, the GPU device instance problem was caused by a memory leak during the unload of the DetailsPage, which has also been resolved with the implementation of the singleton instance too.

The sample has been fixed and updated to incorporate these improvements.

We look forward to receiving your new feedback.

Regards,
Jorge

**Closed as completed by Jorgemagic** 2023-12-20 11:27 UTC
